on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: Determine npm tag
        id: npm_tag
        run: |
          version=$(node -p "require('./package.json').version")
          if [[ $version == *"-rc"* ]]; then
            echo "tag=rc" >> $GITHUB_ENV
          else
            echo "tag=latest" >> $GITHUB_ENV
          fi
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ env.tag }}
          ignore-scripts: false
